spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boilerplate?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
  flyway:
    locations: classpath:/database/migrations
  mail:
    host: smtp.gmail.com
    username: xxxx@gmail.com
    password: xxxxx
    port: 587
    properties.mail.smtp.starttls.enable: true

server:
  port: 8085

custom:
  serverUrl: 'http://localhost:8080'
  verificationTokenExpirationTimeInDays: 30



